### PR TITLE
refactor: remove nix, introduce venv

### LINKED ISSUE #61: Remove nix in favour of venv
Currently, we use nix to manage python packages, but a more standard approach supported better by IDEs is to use python virtual environments. In my opinion, nix adds quite a bit of complexity (and flexibility) that we don't really need in the mongoose. Therefore I'd like to propose to use a less flexible but more simple tool for managing python packages: [virtual environments](https://docs.python.org/3/library/venv.html).

### PR DESCRIPTION
**Pull request by stickyPiston**
closes #61

### CODE REVIEW

**Comment by SamStaijen** [comment]
wouldn't the amazing world of docker remove version management for the end-user?

**Comment by stickyPiston** [comment]
Yes, it would, but I'd rather have that in a separate PR. After all, this repository doesn't have a dev container setup yet, which could automate that for the developer.

**Review by SilasPeters — CHANGES_REQUESTED** [review]
If you are using pyenv, you could add a `.python-version` file containing `3.9`. Then with just `pyenv sync` one can enable and install the right version. Also, then the version can be abstracted from the readme.

Using venv is a good choice, but perhaps pyenv-virtualenv might be an interesting wrapper. Then you don't need to think about using venv from within the right python version.

In general, so I read, virtualenv has more features than venv.

Frankly, I'm only familiar with pyenv, but I believe that we can simplify some of the steps a user has to take.

**Comment by stickyPiston** [comment]
> Using venv is a good choice, but perhaps pyenv-virtualenv might be an interesting wrapper. Then you don't need to think about using venv from within the right python version.

One thing to note, though, is that pyenv does not support windows officially, so we can't only rely on pyenv.

> If you are using pyenv, you could add a .python-version file containing 3.9. Then with just pyenv sync one can enable and install the right version. Also, then the version can be abstracted from the readme.

A `.python-version` file does sound like a good addition.

> In general, so I read, virtualenv has more features than venv.

From what I can see from [virtualenv's website](https://virtualenv.pypa.io/en/latest/) the extra features are not really relevant for us.  But we can mention virtualenv in the readme as an alternative for venv if we want that.

**Comment by SilasPeters** [comment]
If there is no Windows support, ~duck windows~ then we should just keep this solution. I would like to see the `.pytnon-versio` file though

**Comment by SilasPeters** [comment]
> If there is no Windows support, ~duck windows~ then we should just keep this solution. I would like to see the `.pytnon-versio` file though

_With_ the readme suggesting `pyenv sync` to install on Linux

**Comment by SilasPeters** [comment]
Have not tested it though

**Pull request closed without merging**
