### PR TITLE
Custom Admin view

### PR DESCRIPTION
**Pull request by Mstiekema**
Opening a PR so I can drop down some questions here that can be answered in the future by me or someone else :)

### CODE REVIEW

**Comment by Mstiekema** [comment]
Question: At the moment we have an "Added" property in the TopUpTransaction. Should this replaced by a value in ["Pin", "Cash", "Sales"]?

**Comment by Mstiekema** [comment]
Question 2: When do we have the MVP? What other features need to be implemented before we can test with this at Sticky?

**Comment by Mstiekema** [comment]
Question 3: How do we want to display the transactions? Multiple tables you can switch between? Everything into one? How do we display the products in the product transaction?

**Comment by Mstiekema** [comment]
Happy with the current state of the admin view. I think it's production ready! Can be viewed on staging.

**Comment by SilasPeters** [comment]
I believe this closes #25

**Pull request merged**
